const SonicRelayAppAccess = () => {
  return (
    <main className="min-h-screen bg-background">
      <section className="container mx-auto max-w-5xl px-4 py-12 md:py-16">
        <p className="text-sm font-semibold uppercase tracking-[0.25em] text-primary">
          SonicRelay
        </p>
        <h1 className="mt-3 text-3xl font-bold tracking-tight md:text-4xl">
          App Access, Permissions, and Reviewer Notes
        </h1>
        <p className="mt-3 text-muted-foreground">
          Use this as the reviewer-facing source of truth while filling Play Console.
        </p>

        <div className="mt-8 grid gap-6 md:grid-cols-2">
          <section className="rounded-2xl border bg-card p-6 shadow-sm">
            <h2 className="text-xl font-semibold text-foreground">App access</h2>
            <p className="mt-3 leading-7 text-muted-foreground">
              SonicRelay requires an account and a running SonicRelay backend. The
              full streaming flow also requires a Windows publisher device to create a
              session code. Provide reviewer credentials and any temporary session
              instructions inside Play Console App access, not on this public page.
            </p>
          </section>

          <section className="rounded-2xl border bg-card p-6 shadow-sm">
            <h2 className="text-xl font-semibold text-foreground">Ads declaration</h2>
            <p className="mt-3 leading-7 text-muted-foreground">
              Suggested Play Console answer: No, the app does not contain ads. No ad
              SDK, banner, interstitial, rewarded ad, or native ad behavior was
              identified in the reviewed Flutter dependency list.
            </p>
          </section>

          <section className="rounded-2xl border bg-card p-6 shadow-sm">
            <h2 className="text-xl font-semibold text-foreground">Target audience</h2>
            <p className="mt-3 leading-7 text-muted-foreground">
              SonicRelay is a technical personal audio utility. It is not designed
              specifically for children. Choose the final target age groups in Play
              Console according to the public distribution strategy.
            </p>
          </section>

          <section className="rounded-2xl border bg-card p-6 shadow-sm">
            <h2 className="text-xl font-semibold text-foreground">Content rating notes</h2>
            <p className="mt-3 leading-7 text-muted-foreground">
              The app has account login, private device sessions, and remote audio
              playback controlled by the user. It does not include public chat, public
              social sharing, gambling, purchases, or advertising. The final rating
              must come from the official Play Console questionnaire.
            </p>
          </section>
        </div>

        <section className="mt-8 rounded-2xl border bg-card p-6 shadow-sm">
          <h2 className="text-2xl font-semibold text-foreground">Permissions and platform behavior</h2>
          <div className="mt-6 overflow-x-auto">
            <table className="w-full min-w-[760px] border-collapse text-left text-sm">
              <thead>
                <tr className="border-b text-foreground">
                  <th className="py-3 pr-4 font-semibold">Item</th>
                  <th className="py-3 pr-4 font-semibold">Purpose</th>
                  <th className="py-3 font-semibold">User data impact</th>
                </tr>
              </thead>
              <tbody className="text-muted-foreground">
                <tr className="border-b">
                  <td className="py-3 pr-4 font-medium text-foreground">android.permission.INTERNET</td>
                  <td className="py-3 pr-4">Connect to the SonicRelay API, WebSocket signaling endpoint, and WebRTC peers.</td>
                  <td className="py-3">Used for login, device registration, session join, signaling, and media connectivity.</td>
                </tr>
                <tr>
                  <td className="py-3 pr-4 font-medium text-foreground">PROCESS_TEXT query visibility</td>
                  <td className="py-3 pr-4">Generated by Flutter engine support for text processing integration.</td>
                  <td className="py-3">No contacts, messages, photos, files, or location access.</td>
                </tr>
              </tbody>
            </table>
          </div>
        </section>

        <section className="mt-8 rounded-2xl border bg-card p-6 shadow-sm">
          <h2 className="text-2xl font-semibold text-foreground">Reviewer instructions</h2>
          <ol className="mt-3 list-decimal space-y-2 pl-6 leading-7 text-muted-foreground">
            <li>Install and open the Android viewer.</li>
            <li>Sign in using the test credentials provided privately in Play Console.</li>
            <li>Confirm the app registers the viewer device and opens the session join flow.</li>
            <li>Enter a valid temporary session code generated by the Windows publisher test environment.</li>
            <li>Verify the listener screen shows signaling and WebRTC connection state.</li>
          </ol>
          <p className="mt-4 leading-7 text-muted-foreground">
            If no live publisher is available during review, provide clear reviewer
            notes explaining the dependency on the Windows publisher and backend test
            environment. Otherwise the reviewer will stare at a waiting screen and,
            against all odds, that will not count as product-market fit.
          </p>
        </section>

        <section className="mt-8 rounded-2xl border bg-card p-6 shadow-sm">
          <h2 className="text-2xl font-semibold text-foreground">Publishing blocker to verify</h2>
          <p className="mt-3 leading-7 text-muted-foreground">
            If the production Android app lets users create accounts in-app, it must
            also provide an in-app account deletion entry point and an external account
            deletion URL. This public documentation includes the external URL page;
            the app implementation still needs to match the final production behavior.
          </p>
        </section>
      </section>
    </main>
  );
};

export default SonicRelayAppAccess;
