const TheUniverseDecidesAppAccess = () => {
  return (
    <main className="min-h-screen bg-background">
      <section className="container mx-auto max-w-5xl px-4 py-12 md:py-16">
        <p className="text-sm font-semibold uppercase tracking-[0.25em] text-primary">
          The Universe Decides
        </p>
        <h1 className="mt-3 text-3xl font-bold tracking-tight md:text-4xl">
          App Access, Permissions, and Policy Declarations
        </h1>
        <p className="mt-3 text-muted-foreground">
          Use this as the reviewer-facing source of truth while filling Play Console.
        </p>

        <div className="mt-8 grid gap-6 md:grid-cols-2">
          <section className="rounded-2xl border bg-card p-6 shadow-sm">
            <h2 className="text-xl font-semibold text-foreground">App access</h2>
            <p className="mt-3 leading-7 text-muted-foreground">
              No login, subscription, invite code, private area, or test credential is
              required. Reviewers can open the app and access all core features from
              the main navigation.
            </p>
          </section>

          <section className="rounded-2xl border bg-card p-6 shadow-sm">
            <h2 className="text-xl font-semibold text-foreground">Ads declaration</h2>
            <p className="mt-3 leading-7 text-muted-foreground">
              Suggested Play Console answer: No, the app does not contain ads. No ad
              SDK, banner, interstitial, rewarded ad, or native ad behavior is used.
            </p>
          </section>

          <section className="rounded-2xl border bg-card p-6 shadow-sm">
            <h2 className="text-xl font-semibold text-foreground">Target audience</h2>
            <p className="mt-3 leading-7 text-muted-foreground">
              The app is a general-purpose utility and entertainment tool. It is not
              designed specifically for children. Choose the final target age groups
              in Play Console according to the current store listing and distribution
              strategy.
            </p>
          </section>

          <section className="rounded-2xl border bg-card p-6 shadow-sm">
            <h2 className="text-xl font-semibold text-foreground">Content rating notes</h2>
            <p className="mt-3 leading-7 text-muted-foreground">
              The app contains random decision tools, playing cards, dice, and tarot
              cards. It does not include real-money gambling, betting, violent content,
              sexual content, user chat, public user-generated content, or purchases.
              The final rating must come from the official Play Console questionnaire.
            </p>
          </section>
        </div>

        <section className="mt-8 rounded-2xl border bg-card p-6 shadow-sm">
          <h2 className="text-2xl font-semibold text-foreground">Permissions and platform behavior</h2>
          <div className="mt-6 overflow-x-auto">
            <table className="w-full min-w-[760px] border-collapse text-left text-sm">
              <thead>
                <tr className="border-b text-foreground">
                  <th className="py-3 pr-4 font-semibold">Item</th>
                  <th className="py-3 pr-4 font-semibold">Purpose</th>
                  <th className="py-3 font-semibold">User data impact</th>
                </tr>
              </thead>
              <tbody className="text-muted-foreground">
                <tr className="border-b">
                  <td className="py-3 pr-4 font-medium text-foreground">android.permission.INTERNET</td>
                  <td className="py-3 pr-4">Fetch random integers from Random.org and load the developer profile from GitHub API.</td>
                  <td className="py-3">No app account or analytics identifier is sent by the app.</td>
                </tr>
                <tr className="border-b">
                  <td className="py-3 pr-4 font-medium text-foreground">Quick Settings tile services</td>
                  <td className="py-3 pr-4">Allow users to add coin and d20 shortcuts to the Android quick settings panel.</td>
                  <td className="py-3">Used only to open the app into the selected action.</td>
                </tr>
                <tr>
                  <td className="py-3 pr-4 font-medium text-foreground">PROCESS_TEXT query visibility</td>
                  <td className="py-3 pr-4">Generated by Flutter engine support for text processing integration.</td>
                  <td className="py-3">No contacts, SMS, photos, location, or account data access.</td>
                </tr>
              </tbody>
            </table>
          </div>
        </section>

        <section className="mt-8 rounded-2xl border bg-card p-6 shadow-sm">
          <h2 className="text-2xl font-semibold text-foreground">Reviewer instructions</h2>
          <ol className="mt-3 list-decimal space-y-2 pl-6 leading-7 text-muted-foreground">
            <li>Install and open the app.</li>
            <li>Use the bottom navigation to test Coin, Dice, Cards, Lists, Tarot, and About me.</li>
            <li>Disconnect the network to verify the Random.org fallback notice and local randomness behavior.</li>
            <li>On supported Android versions, use the About me screen to request coin or d20 Quick Settings shortcuts.</li>
          </ol>
        </section>
      </section>
    </main>
  );
};

export default TheUniverseDecidesAppAccess;
